---
title: "02_回帰1"
output: html_document
---

## 例題1：⾃動⾞の速度と停⽌距離

### データの確認

```{r}
library(tidyverse)
library(caret)

my_data <- cars
```

データの件数（次元）

```{r}
dim(my_data)
```

```{r}
head(my_data)
```

散布図

```{r}
ggplot(data = my_data, mapping = aes(x = speed, y = dist)) +
  geom_point()
```

### 訓練データとテストデータ

```{r}
#ランダムサンプリング
my_index <- sample(1:nrow(my_data), 0.2 * nrow(my_data))

#授業と同じ結果にする
my_index <- c(5, 6, 10, 12, 20, 25, 31, 34, 40, 48)
my_train <- my_data[-my_index,]
my_test <- my_data[my_index,]
```

```{r}
#このコードは理解できなくていい
tmp <- rbind(data.frame(my_train, data = "training"), data.frame(my_test, data = "test"))
ggplot(data = tmp, mapping = aes(x = speed, y = dist, color = data)) +
  geom_point() +
  scale_color_manual(values = c(training = "cyan", test = "magenta"))
```

### K最近傍法（k-nearest neighbor, k-NN）

下の結果を見ながら，速度が（speed）が21.5の場合の停止距離（dist）を1近傍法で予測せよ。

```{r}
my_train
```

練習：速度が5の場合はどうか。

#### 学習

```{r}
(my_result <- train(form = dist ~ speed, data = my_train, method = "knn"))
```

#### 結果

```{r}
#このコードは理解できなくていい
tmp <- data.frame(speed = seq(from = min(my_data$speed), to = max(my_data$speed), length.out = 100))
tmp$dist <- predict(object = my_result, newdata = tmp)

ggplot(mapping = aes(x = speed, y = dist)) +
  geom_point(data = my_train, color = "cyan") +
  geom_line(data = tmp)
```

#### 性能評価

```{r}
my_prediction <- predict(object = my_result, newdata = my_test)
(my_test2 <- data.frame(my_test, prediction = my_prediction))
```

```{r}
#このコードは理解できなくていい
tmp <- data.frame(speed = seq(from = min(my_data$speed), to = max(my_data$speed), length.out = 100))
tmp$dist <- predict(object = my_result, newdata = tmp)

ggplot(mapping = aes(x = speed, y = dist)) +
  geom_point(data = my_test2, color = "magenta") +
  geom_line(data = tmp) +
  geom_linerange(data = my_test2, mapping = aes(ymin = dist, ymax = prediction), color = "green")
```

残差（residual）

```{r}
my_test2$residual <- my_test2$dist - my_test2$prediction
my_test2
```

RMSE（Root Mean Square Error）

```{r}
sqrt(mean(my_test2$residual^2))
```

テストデータにおけるRMSE

```{r}
my_prediction <- predict(object = my_result, newdata = my_train)
my_residual <- my_train$dist - my_prediction
sqrt(mean(my_residual^2))
```

**レポート課題：訓練データとテストデータをランダムサンプリングで作り，訓練データでK最近傍法を実行し，テストデータにおけるRMSEを求めてください。この作業を5回試み，結果を報告してください。**